### ISSUE TITLE
Удалить все сообщения (везде) кроме личных

### ISSUE THREAD

**Issue by MANCrimSon** [en9inerd/tgeraser#7]
Подскажите пожалуйста, какой командой я могу удалить все сообщения (везде) кроме личных?

**Comment by en9inerd** [comment]
@MANCrimSon there is no such option/argument to exclude `Saved Messages` if you mean this. To delete ALL messages from all chats/channels/dialogs that you have in dialog list you can use `-w --wipe-everything` option/argument, I'm not sure if it works properly since I didn't test this for a long time but you can try.

**Comment by MANCrimSon** [comment]
@en9inerd I need to delete all messages except for personal conversations. The -w command deletes personal conversations as well.

**Comment by en9inerd** [comment]
@MANCrimSon I just released new version with improvements, let me know if `tgeraser -w -entity-type chat` works. Also you can use `tgeraser -w -entity-type chat && tgeraser -w -entity-type channel` to delete all messages from all chats and all posts from all your channels

**Comment by MANCrimSon** [comment]
> @MANCrimSon I just released new version with improvements, let me know if `tgeraser -w -entity-type chat` works. Also you can use `tgeraser -w -entity-type chat && tgeraser -w -entity-type channel` to delete all messages from all chats and all posts from all your channels

Everything is working, just need --entity-type. For example, I input it like this: tgeraser session 12345 -w --entity-type channel.
Thank you.
